name: Create Pull Request

on:
  push:
    branches:
      - 'release-*.*.*'

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "Created pull request"
          title: "Pull Request Title"
          body: "Pull Request Description"
          branch: "${{ github.event.ref }}"
          base: "main"

      - name: Approve Pull Request
        run: |
          pull_request_url="https://api.github.com/repos/${{ github.repository }}/pulls/${{ steps.create_pr.outputs.pull-request }}"
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "${pull_request_url}/reviews" \
            -d '{
              "event": "APPROVE"
            }'
