name: Publish to npm V2

on:
  workflow_dispatch:
    inputs:

      # Input для ввода features changes (для CHANGELOG.md)
      features:
        type: text
        description: changelog features
        default: ''

      # Input для ввода bugfixes changes (для CHANGELOG.md)
      bugfixes:
        type: text
        description: changelog bugfixes
        default: ''

      # Input для ввода breaking changes (для CHANGELOG.md)
      breaking-changes:
        type: text
        description: changelog breaking changes
        default: ''

      # Select для выбора версии
      version:
        type: choice
        description: Choose which version to release
        options:
          - beta
          - patch
          - minor
          - major

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      # Переключение на выбранную при запуске action ветку и скачивание файлов в окружение.
      - name: Checkout
        uses: actions/checkout@v3

      # Установка учётных данных bot как gitUser в текущем окружении (для release commit).
      # Извлечение имени текущей ветки.
      - name: Git config
        run: |
          git config user.name ${{ secrets.BOT_USERNAME }}
          git config user.email ${{ secrets.BOT_EMAIL }}
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      # Установка зависимостей.
      - name: Install dependencies
        run: yarn

      # Прогон тестов
      #- name: Run tests
      #  run: yarn test

      # Сборка приложения в /.publish.
      - name: Build app
        run: yarn build

      # Установка npm токена для возможности публикации.
      - name: Set NPM Token
        uses: filipstefansson/set-npm-token-action@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      # Извлечение sha последнего commit из выбранной ветки (нужно для построения версии beta).
      - name: Set last commit sha for beta release
        if: github.event.inputs.version == 'beta'
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # Создание временных файлов для changelog.
      - name: Create changelog temp files
        run: |
          echo "${{ github.event.inputs.features }}" > changelog_features.tmp
          echo "${{ github.event.inputs.bugfixes }}" > changelog_bugfixes.tmp
          echo "${{ github.event.inputs.breaking-changes }}" > changelog_breaking_changes.tmp

      # Извлечение текущей версии приложения для выпуска beta пакета.
      - name: Get current version for beta
        if: github.event.inputs.version == 'beta'
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      # Публикация выбранной версии в npm.
      - name: Publish ${{ github.event.inputs.version }} version
        run: yarn release:${{ github.event.inputs.version }}
        env:
          BETA_VERSION: ${{ steps.package-version.outputs.current-version }}-beta.${{ steps.vars.outputs.sha_short }}
          BRANCH: ${{ steps.extract_branch.outputs.branch}}

      # Извлечение текущей (актуальной) версии приложения для выпуска patch|minor|major пакета.
      - name: Get current version for release
        if: github.event.inputs.version != 'beta'
        id: package-version-for-release
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      # Заполнение файла changelog и выполнение release commit && push в выбранную ветку.
      - name: Push changes to ${{ steps.extract_branch.outputs.branch}} branch about release
        if: github.event.inputs.version != 'beta'
        run: |
          yarn changelog
          yarn create-release-commit
        env:
          BRANCH: ${{ steps.extract_branch.outputs.branch}}
          VERSION: ${{ steps.package-version-for-release.outputs.current-version }}
          SEMANTIC_VERSION: ${{ github.event.inputs.version }}
          FEATURES: ${{ github.event.inputs.features }}
          BUGFIXES: ${{ github.event.inputs.bugfixes }}
          BREAKING_CHANGES: ${{ github.event.inputs.breaking-changes }}
