name: Publish to npm V2

on:
  workflow_dispatch:
    inputs:

      # Input для ввода features changes (для CHANGELOG.md)
      features:
        type: text
        description: changelog features

      # Input для ввода bugfixes changes (для CHANGELOG.md)
      bugfixes:
        type: text
        description: changelog bugfixes

      # Input для ввода breaking changes (для CHANGELOG.md)
      breaking-changes:
        type: text
        description: changelog breaking changes

      # Select для выбора версии
      version:
        type: choice
        description: Choose which version to release
        options:
          - beta
          - patch
          - minor
          - major

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:

      # Переключение на выбранную при запуске action ветку
      # Установка учетных данных бота как gitUser в текущем окружении (для release commit от имени бота)
      - uses: actions/checkout@v3
      - run: |
          git config user.name ${{ secrets.BOT_USERNAME }}
          git config user.email ${{ secrets.BOT_EMAIL }}
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      # Установка зависимостей
      - name: Install dependencies
        run: yarn

      # Прогон тестов
      - name: Install dependencies
        run: yarn test

      # Сборка приложения в /.publish
      - name: Build app
        run: yarn build

      # Установка npm токена для возможности публикации
      - name: Set NPM Token
        uses: filipstefansson/set-npm-token-action@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      # Извлечение sha последнего commit из выбранной ветки (нужно для построения версии beta)
      - name: Set last commit sha for beta release
        if: github.event.inputs.version == 'beta'
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # Извлечение текущей (актуальной) версии приложения (нужно для построения версии beta)
      - name: Get current version for beta release
        if: github.event.inputs.version == 'beta'
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      # Создание временных файлов для changelog
      - name: Create changelog temp files
        run: |
          echo "${{ steps.checkout.outputs }}"
          echo "${{ github.event.inputs.features }}" > changelog_features.tmp
          echo "${{ github.event.inputs.bugfixes }}" > changelog_bugfixes.tmp
          echo "${{ github.event.inputs.breaking-changes }}" > changelog_breaking_changes.tmp

      - name: Publish ${{ github.event.inputs.version }} version
        run: npm run lib:release:${{ github.event.inputs.version }}
        env:
          BETA_VERSION: ${{ steps.package-version.outputs.current-version }}-beta.${{ steps.vars.outputs.sha_short }}
          BRANCH: ${{ steps.extract_branch.outputs.branch}}

