name: Post push check

on:
  push


jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      # Переключение на выбранную при запуске action ветку и скачивание файлов в окружение.
      - name: Checkout
        uses: actions/checkout@v3

      # Установка зависимостей.
      - name: Install dependencies
        run: echo "Тут как бы yarn install"

      # Прогон тестов
      - name: Run tests
        run: echo "Тут как бы прошли тесты и все хорошо yarn test"

      - name: Make API request
        id: release_request
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{
              "tag_name": "v1.0.0",
              "target_commitish": "master",
              "name": "v1.0.0",
              "body": "Description of the release",
              "draft": false,
              "prerelease": false,
              "generate_release_notes": false
                }' \
            https://api.github.com/repos/core-ds/test/releases
        env:
          TOKEN: ${{ secrets.BOT_AUTH_TOKEN }}

