name: Post push check

on:
  push


jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      # Переключение на выбранную при запуске action ветку и скачивание файлов в окружение.
      - name: Checkout
        uses: actions/checkout@v3

      # Установка зависимостей.
      - name: Install dependencies
        run: yarn

      # Прогон тестов
      - name: Run tests
        run: echo "Тут как бы прошли тесты и все хорошо"
