name: Create Pull Request

on:
  push:
    branches:
      - 'release-*.*.*'


jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "Created pull request"
          title: "Pull Request Title"
          body: "Pull Request Description"
          branch: "${{ github.event.ref }}"
          base: "main"
