name: SASHA

on:
  workflow_dispatch:
    inputs:

      # Input для ввода features changes (для CHANGELOG.md)
      features:
        type: text
        description: changelog features
        default: ''

      # Input для ввода bugfixes changes (для CHANGELOG.md)
      bugfixes:
        type: text
        description: changelog bugfixes
        default: ''

      # Input для ввода breaking changes (для CHANGELOG.md)
      breaking-changes:
        type: text
        description: changelog breaking changes
        default: ''

      # Select для выбора версии
      version:
        type: choice
        description: Choose which version to release
        required: true
        options:
          - beta
          - patch
          - minor
          - major

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      # Переключение на выбранную при запуске action ветку и скачивание файлов в окружение.
      - name: Checkout
        uses: actions/checkout@v3

      # Установка учётных данных bot как gitUser в текущем окружении (для release commit).
      # Извлечение имени текущей ветки.
      - name: Git config
        run: |
          git config user.name ${{ secrets.BOT_USERNAME }}
          git config user.email ${{ secrets.BOT_EMAIL }}
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      # Установка npm токена для возможности публикации.
      - name: Set NPM Token
        uses: filipstefansson/set-npm-token-action@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      # Извлечение sha последнего commit из выбранной ветки (нужно для построения версии beta).
      - name: Set last commit sha for beta release
        if: github.event.inputs.version == 'beta'
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # Извлечение текущей версии приложения для выпуска beta пакета.
      - name: Get current version for beta
        if: github.event.inputs.version == 'beta'
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Get repository URL
        run: |
          echo "Repository URL: https://github.com/${{ env.GITHUB_REPOSITORY }}"

      - name: TEST CHECK
        run: |
          echo "custom-sha: ${{ steps.vars.outputs.sha_short }}"
          echo "GITHUB_SHA: ${{ github.sha }}"
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "Ветка: ${{ env.BRANCH }}"
          echo "GITHUB_WORKFLOW_SHA: ${{ github.workflow_sha }}"
          echo "GITHUB_ACTION_REPOSITORY: ${{ github.action_repository }}"
          echo "GITHUB_HEAD_REF: ${{ github.head_ref }}"
        env:
          BRANCH: $(basename $GITHUB_REF)
